// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Infrastructure.Data;

#nullable disable

namespace Recipes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222152505_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Recipes.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Recipes.Core.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500.0,
                            Name = "Cerdo",
                            RecipeId = 1,
                            Unit = "gramos"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1.0,
                            Name = "Piña",
                            RecipeId = 1,
                            Unit = "pieza"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3.0,
                            Name = "Huevo",
                            RecipeId = 2,
                            Unit = "unidades"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50.0,
                            Name = "Pecorino",
                            RecipeId = 2,
                            Unit = "gramos"
                        });
                });

            modelBuilder.Entity("Recipes.Core.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTimeMinutes = 45,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 25, 4, 989, DateTimeKind.Utc).AddTicks(3666),
                            Description = "Clásico mexicano",
                            ImageUrl = "https://theeburgerdude.com/wp-content/uploads/2024/11/Al-Pastor-01-1024x1024.jpg",
                            Instructions = "Marinar la carne y asar.",
                            Title = "Tacos al Pastor"
                        },
                        new
                        {
                            Id = 2,
                            CookingTimeMinutes = 20,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 25, 4, 989, DateTimeKind.Utc).AddTicks(3697),
                            Description = "Receta original italiana",
                            ImageUrl = "https://www.informacibo.it/wp-content/uploads/2018/04/carbonara.jpg",
                            Instructions = "Mezclar huevo y queso.",
                            Title = "Pasta Carbonara"
                        });
                });

            modelBuilder.Entity("Recipes.Core.Entities.Ingredient", b =>
                {
                    b.HasOne("Recipes.Core.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Recipes.Core.Entities.Recipe", b =>
                {
                    b.HasOne("Recipes.Core.Entities.Category", null)
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Recipes.Core.Entities.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Recipes.Core.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
